### ISSUE TITLE
Cannot read property 'name' of undefined at no-array-index-key.js:146:25 - And eslint-config-airbnb@14.0.0  invalid

### ISSUE THREAD

**Issue by lasergoat** [airbnb/javascript#1247]
Running our good old install command:

```
(
  export PKG=eslint-config-airbnb;
  npm info "$PKG@latest" peerDependencies --json | command sed 's/[\{\},]//g ; s/: /@/g' | xargs npm install --save-dev "$PKG@latest"
)
```

Today gave this:

```
├─┬ eslint@3.13.1  invalid
│ ├── file-entry-cache@2.0.0 
│ ├── natural-compare@1.4.0 
│ ├── strip-bom@3.0.0 
│ └── strip-json-comments@2.0.1 
├─┬ eslint-config-airbnb@14.0.0  invalid
│ └── eslint-config-airbnb-base@11.0.1 
├── eslint-plugin-import@2.2.0 
├── eslint-plugin-jsx-a11y@3.0.2 
└── eslint-plugin-react@6.9.0 
```

<img width="386" alt="screen shot 2017-01-10 at 4 59 04 pm" src="https://cloud.githubusercontent.com/assets/15964/21828541/9cf1da26-d756-11e6-930c-2af08e1b7035.png">

I don't see what is invalid about that since those versions are all listed on npm. Running my lint script gives an error about:

```
Cannot read property 'name' of undefined
TypeError: Cannot read property 'name' of undefined
    at /Users/user/project/node_modules/eslint-plugin-react/lib/rules/no-array-index-key.js:146:25
    at Array.forEach (native)
    at EventEmitter.CallExpression (/Users/user/project/node_modules/eslint-plugin-react/lib/rules/no-array-index-key.js:145:28)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
    at NodeEventGenerator.enterNode (/Users/user/project/node_modules/eslint/lib/util/node-event-generator.js:39:22)
    at CodePathAnalyzer.enterNode (/Users/user/project/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:607:23)
    at CommentEventGenerator.enterNode (/Users/user/project/node_modules/eslint/lib/util/comment-event-generator.js:97:23)
    at Controller.enter (/Users/user/project/node_modules/eslint/lib/eslint.js:928:36)
    at Controller.__execute (/Users/user/project/node_modules/estraverse/estraverse.js:397:31)
```

Has anyone else seen this?

**Comment by ljharb** [comment]
What does your `package.json` look like?

**Comment by davidkpiano** [comment]
@ljharb This is their dependencies:

```
  "devDependencies": {
    "chai": "^3.5.0",
    "chai-as-promised": "^5.2.0",
    "chai-subset": "^1.2.2",
    "eslint": "~3.12.2",
    "eslint-config-airbnb": "~13.0.0",
    "eslint-config-airbnb-base": "^10.0.1",
    "eslint-plugin-import": "~2.2.0",
    "eslint-plugin-jsx-a11y": "~2.2.3",
    "eslint-plugin-react": "~6.8.0",
    "husky": "^0.11.4",
    "jsdom": "^8.5.0",
    "mocha": "^2.4.5",
    "moxios": "^0.3.0",
    "redux-mock-store": "0.0.6",
    "redux-test-store": "^0.4.0",
    "sinon": "^1.17.6",
    "sinon-chai": "^2.8.0"
  },
  "dependencies": {
    "autoprefixer": "^6.3.1",
    "axios": "^0.15.3",
    "babel-core": "^6.9.0",
    "babel-eslint": "^6.1.0",
    "babel-loader": "^6.2.4",
    "babel-plugin-lodash": "^3.1.4",
    "babel-polyfill": "^6.9.0",
    "babel-preset-es2015": "^6.9.0",
    "babel-preset-react": "^6.3.13",
    "babel-preset-stage-0": "^6.3.13",
    "babel-register": "^6.8.0",
    "classnames": "^2.2.4",
    "copy-to-clipboard": "^3.0.5",
    "css-loader": "^0.23.1",
    "dateformat": "^1.0.12",
    "es6-promise": "^4.0.5",
    "eslint": "~2.13.1",
    "eslint-config-airbnb": "^9.0.1",
    "extract-text-webpack-plugin": "^1.0.1",
    "history": "^1.17.0",
    "html-webpack-plugin": "^2.7.1",
    "icepick": "^1.3.0",
    "lodash": "^4.13.1",
    "lodash-webpack-plugin": "^0.8.0",
    "lodash.uniqby": "^4.3.0",
    "material-design-iconic-font": "^2.2.0",
    "moment": "^2.13.0",
    "node-sass": "^3.4.2",
    "react": "^15.4.1",
    "react-addons-shallow-compare": "15.3.1",
    "react-autocomplete": "^1.3.1",
    "react-dates": "^4.1.0",
    "react-dom": "^15.4.1",
    "react-flip-move": "^2.4.2",
    "react-modal": "^1.4.0",
    "react-portal": "^3.0.0",
    "react-redux": "^4.4.6",
    "react-redux-form": "1.5.0",
    "react-router": "^2.0.1",
    "redux": "^3.6.0",
    "redux-devtools-extension": "^1.0.0",
    "redux-localstorage": "^0.4.0",
    "redux-logger": "^2.6.1",
    "redux-saga": "^0.10.4",
    "redux-thunk": "^2.0.1",
    "request": "^2.67.0",
    "rrule": "^2.1.0",
    "sass-loader": "^3.2.0",
    "shallowequal": "^0.2.2",
    "simple-node-intercom-io": "^1.0.1",
    "validator": "^5.1.0",
    "victory": "^0.5.1",
    "webpack": "^1.13.1",
    "webpack-cli": "^1.0.0",
    "webpack-dev-server": "^1.14.1"
  }
```

**Comment by lasergoat** [comment]
@ljharb actually this is the latest result of me running the install command:

```json
  "devDependencies": {
    "chai": "^3.5.0",
    "chai-as-promised": "^5.2.0",
    "chai-subset": "^1.2.2",
    "eslint": "^3.13.1",
    "eslint-config-airbnb": "^14.0.0",
    "eslint-plugin-import": "^2.2.0",
    "eslint-plugin-jsx-a11y": "^3.0.2",
    "eslint-plugin-react": "^6.9.0",
    "husky": "^0.11.4",
    "jsdom": "^8.5.0",
    "mocha": "^2.4.5",
    "moxios": "^0.3.0",
    "redux-mock-store": "0.0.6",
    "redux-test-store": "^0.4.0",
    "sinon": "^1.17.6",
    "sinon-chai": "^2.8.0"
  },
  "dependencies": {
    "autoprefixer": "^6.3.1",
    "axios": "^0.15.3",
    "babel-core": "^6.9.0",
    "babel-eslint": "^6.1.0",
    "babel-loader": "^6.2.4",
    "babel-plugin-lodash": "^3.1.4",
    "babel-polyfill": "^6.9.0",
    "babel-preset-es2015": "^6.9.0",
    "babel-preset-react": "^6.3.13",
    "babel-preset-stage-0": "^6.3.13",
    "babel-register": "^6.8.0",
    "classnames": "^2.2.4",
    "copy-to-clipboard": "^3.0.5",
    "css-loader": "^0.23.1",
    "dateformat": "^1.0.12",
    "es6-promise": "^4.0.5",
    "eslint": "~2.13.1",
    "eslint-config-airbnb": "^9.0.1",
    "extract-text-webpack-plugin": "^1.0.1",
    "history": "^1.17.0",
    "html-webpack-plugin": "^2.7.1",
    "icepick": "^1.3.0",
    "lodash": "^4.13.1",
    "lodash-webpack-plugin": "^0.8.0",
    "lodash.uniqby": "^4.3.0",
    "material-design-iconic-font": "^2.2.0",
    "moment": "^2.13.0",
    "node-sass": "^3.4.2",
    "react": "^15.4.1",
    "react-addons-shallow-compare": "15.3.1",
    "react-autocomplete": "^1.3.1",
    "react-dates": "^4.1.0",
    "react-dom": "^15.4.1",
    "react-flip-move": "^2.4.2",
    "react-modal": "^1.4.0",
    "react-portal": "^3.0.0",
    "react-redux": "^4.4.6",
    "react-redux-form": "1.5.0",
    "react-router": "^2.0.1",
    "redux": "^3.6.0",
    "redux-devtools-extension": "^1.0.0",
    "redux-localstorage": "^0.4.0",
    "redux-logger": "^2.6.1",
    "redux-saga": "^0.10.4",
    "redux-thunk": "^2.0.1",
    "request": "^2.67.0",
    "rrule": "^2.1.0",
    "sass-loader": "^3.2.0",
    "shallowequal": "^0.2.2",
    "simple-node-intercom-io": "^1.0.1",
    "validator": "^5.1.0",
    "victory": "^0.15.0",
    "webpack": "^1.13.1",
    "webpack-cli": "^1.0.0",
    "webpack-dev-server": "^1.14.1"
  }
```

**Comment by ljharb** [comment]
ok, so after running the latest install command, does `npm ls` report any errors?

Your original package.json still had "9.0.0" as the version for eslint-config-airbnb, so that would be invalid.

**Comment by lasergoat** [comment]
@ljharb yes,

`npm ls` gives:

```
npm ERR! invalid: eslint@3.13.1 /Users/daniel/Projects/fattpay-react/node_modules/eslint
npm ERR! invalid: eslint-config-airbnb@14.0.0 /Users/daniel/Projects/fattpay-react/node_modules/eslint-config-airbnb
```
at the very bottom. 

Were did you see a `9.0.0`?

I just tried clearing my global npm cache and clearing my project's node_modules and manually inserting the versions from: 

```
npm info "eslint-config-airbnb@latest" peerDependencies
```

Then `npm i` to no avail. Same error. Is eslint 3.13.1 the right version?

**Comment by lasergoat** [comment]
Here's what I just don't understand...

I made a an empty test project and did npm init then ran the eslint-config-airbnb install command and did `npm ls | eslint` and look at the results... same versions my main project is trying to use:

```
eslint-test@1.0.0 /Users/daniel/Projects/eslintTest
├─┬ eslint@3.13.1
├─┬ eslint-config-airbnb@14.0.0
│ └── eslint-config-airbnb-base@11.0.1
├─┬ eslint-plugin-import@2.2.0
│ ├─┬ eslint-import-resolver-node@0.2.3
│ ├─┬ eslint-module-utils@2.0.0
├─┬ eslint-plugin-jsx-a11y@3.0.2
└─┬ eslint-plugin-react@6.9.0```

**Comment by lasergoat** [comment]
@ljharb I think I found a sustainable solution. We have eslint as a precommit hook (using husky). My solution was to fully remove and say goodbye to eslint. Managing a project through 5 different versioned repos is not something I want to be a part of. Eslint-config-airbnb has been amazing when it works, but at least once a week we have issues with it and I'm at my wit's end. It has 100% become more of a setback for our project. Thanks for the time you've put into these projects - but IMO it needs to just be one package that _just works_.

I'm pretty sure our issue is that one of our other dependencies is including an older version of eslint as a devDependency and I have no way of getting it to _not_ install it - so it's messing everything up.

**Comment by ljharb** [comment]
Yes, that sounds like what's happening - what's the other dependency?

In general though, git hooks are useless as a means of enforcement; what's important is CI. I'd strongly recommend abandoning any git hook tools, rather than abandoning the de facto standard for code quality enforcement in the JS ecosystem, if you had to choose.

**Comment by davidkpiano** [comment]
@ljharb The other dependency is [React-Redux-Form](https://github.com/davidkpiano/react-redux-form) - is there anything regarding dependencies I should address in that repo?

**Comment by lasergoat** [comment]
Git hooks have proven to be more useful to us than CI - obviously our CI does everything too and more, but this way, unlinted code cannot even be pushed up. husky makes it so all team members have the same git hooks -works a lot better than it sounds.

**Comment by ljharb** [comment]
hmm, not that i know of. Could you share the repo itself? If I can reproduce it locally, I can definitely figure out the problem.

**Comment by ljharb** [comment]
Also, what non-standard JS syntaxes are you using? `eslint-plugin-react` does have some bugs with FlowType, for example.

It's possible that specific syntax in a specific file is breaking `eslint-plugin-react` - in which case, we should figure that out and file an issue there.

**Comment by lasergoat** [comment]
@ljharb hmm, i'm not sure which non-standard js syntaxes we are using. We just have normal JSX in the es6 type format.

Good news, I solved the `invalid` part of our problem.. I was somehow including eslint in both dev and normal dependencies:

```
  "devDependencies": {
    "eslint": "^3.13.1",
    "eslint-config-airbnb": "^14.0.0",
    "eslint-plugin-import": "^2.2.0",
    "eslint-plugin-jsx-a11y": "^3.0.2",
    "eslint-plugin-react": "^6.9.0",
  },
  "dependencies": {
    "eslint": "~2.13.1",
    "eslint-config-airbnb": "^9.0.1",
    ...
  }
```

So now I don't get the "invalid" issue. However, when I run `./node_modules/.bin/eslint ./src/* --fix` I am back to getting: 


```
Cannot read property 'name' of undefined
TypeError: Cannot read property 'name' of undefined
```

Is this something I need to ask the eslint-plugin-react team about?

**Comment by ljharb** [comment]
yes, thanks, I see you've filed https://github.com/yannickcr/eslint-plugin-react/issues/1021 - closing this in favor of that.

**Comment by lasergoat** [comment]
thanks!
