### ISSUE TITLE
command `npm test` not works on win 10.

### ISSUE THREAD

**Issue by FrostyLeaf** [airbnb/javascript#1486]
I'm trying to run the tests of this package in win 10, these are my command lines:

```bash
git clone git@github.com:airbnb/javascript.git airbnb
cd airbnb\packages\eslint-config-airbnb
npm i
npm test
```

then I get this:

```bash
> eslint-config-airbnb@15.0.2 pretest D:\repo\airbnb\packages\eslint-config-airbnb
> npm run --silent lint

fs.js:994
  binding.lstat(pathModule._makeLong(path), statValues);
          ^

Error: ENOENT: no such file or directory, lstat 'D:\repo\airbnb\packages\eslint-config-airbnb\*'
    at Error (native)
    at Object.fs.lstatSync (fs.js:994:11)
    at D:\repo\airbnb\packages\eslint-config-airbnb\node_modules\editorconfig-tools\lib\cli.js:83:16
    at Array.forEach (native)
    at D:\repo\airbnb\packages\eslint-config-airbnb\node_modules\editorconfig-tools\lib\cli.js:81:25
    at Array.forEach (native)
    at Object.<anonymous> (D:\repo\airbnb\packages\eslint-config-airbnb\node_modules\editorconfig-tools\lib\cli.js:78:24)
    at Object.<anonymous> (D:\repo\airbnb\packages\eslint-config-airbnb\node_modules\editorconfig-tools\lib\cli.js:276:4)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\repo\airbnb\packages\eslint-config-airbnb\node_modules\editorconfig-tools\bin\index.js:8:11)
```

then I try this:

```bash
.\node_modules\.bin\editorconfig-tools check * rules/* test/*
```

and get the same result.

I really have no idea with this, please help me.

**Comment by FrostyLeaf** [comment]
Oh, I forgot something.
I ran those commands with node 6.11.0 and npm 5.0.4.

**Comment by ljharb** [comment]
In that case, it seems `editorconfig-tools` doesn't work on windows.

I'd recommend filing an issue on their repo: https://github.com/slang800/editorconfig-tools

If there's other issues with this package on windows, I'm happy to reopen this issue.

**Comment by FrostyLeaf** [comment]
OK, thanks a lot.@ljharb
