### ISSUE TITLE
Configuration for rule "jsx-a11y/anchor-has-content" is invalid: Value "" is the wrong type.

### ISSUE THREAD

**Issue by Theo-** [airbnb/javascript#1512]
Hi everyone, I am running into an error that I can't seem to fix on my own, even after looking at previous related issues.

package.json
```
    "eslint": "^4.3.0",
    "eslint-config-airbnb": "^15.1.0",
    "eslint-plugin-import": "^2.7.0",
    "eslint-plugin-jsx-a11y": "^5.1.1",
    "eslint-plugin-react": "^7.1.0",
```

which meets the peerDependecies:
```
{ eslint: '^3.19.0 || ^4.3.0',
  'eslint-plugin-jsx-a11y': '^5.1.1',
  'eslint-plugin-import': '^2.7.0',
  'eslint-plugin-react': '^7.1.0' }
```

However, when running `eslint` I get the following error:
```
/usr/local/lib/node_modules/eslint-config-airbnb/rules/react-a11y.js:
        Configuration for rule "jsx-a11y/anchor-has-content" is invalid:
        Value "" is the wrong type.

Referenced from: airbnb
Referenced from: <project path>/.eslintrc.json
Error: /usr/local/lib/node_modules/eslint-config-airbnb/rules/react-a11y.js:
        Configuration for rule "jsx-a11y/anchor-has-content" is invalid:
        Value "" is the wrong type.

Referenced from: airbnb
Referenced from: <project path>/.eslintrc.json
    at validateRuleOptions (/usr/local/lib/node_modules/eslint/lib/config/config-validator.js:115:15)
    at /usr/local/lib/node_modules/eslint/lib/config/config-validator.js:162:13
    at Array.forEach (native)
    at Object.validate (/usr/local/lib/node_modules/eslint/lib/config/config-validator.js:161:35)
    at load (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:522:19)
    at /usr/local/lib/node_modules/eslint/lib/config/config-file.js:391:36
    at Array.reduceRight (native)
    at applyExtends (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:362:28)
    at load (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:529:22)
    at /usr/local/lib/node_modules/eslint/lib/config/config-file.js:391:36
```

I did try to remove `node_modules` and run `yarn install` or `npm install`, but neither works.

If that helps, I have node `v6.10.3`

**Comment by ljharb** [comment]
It's running a global eslint; you should uninstall that and only use the local one.

**Comment by Theo-** [comment]
@ljharb that did it. Thanks.

For reference, the command that worked was `./node_modules/.bin/eslint <file>`.

**Comment by ljharb** [comment]
I'd recommend running `npx eslint` or running it exclusively from an npm run-script.
