### ISSUE TITLE
"Configuration for rule "jsx-a11y/anchor-has-content" is invalid" error with correct peer dependencies

### ISSUE THREAD

**Issue by OlgaKozlova** [airbnb/javascript#1540]
I looked through similar issues but can't find the solution. I have no globally installed eslint, and peer configurations are correct:

My dev-dependencies:
```
"devDependencies": {
    "eslint": "^4.3.0",
    "eslint-config-airbnb": "^15.1.0",
    "eslint-plugin-import": "^2.7.0",
    "eslint-plugin-jsx-a11y": "^5.1.1",
    "eslint-plugin-react": "^7.1.0"
  }
```

Peer Dependencies:
```
 $ npm info "eslint-config-airbnb@latest" peerDependencies

{ eslint: '^3.19.0 || ^4.3.0',
  'eslint-plugin-jsx-a11y': '^5.1.1',
  'eslint-plugin-import': '^2.7.0',
  'eslint-plugin-react': '^7.1.0' }

```
.eslintrc
```
{
  "extends": "airbnb"
}
```

Error: 
```
Error: <pathToProject>\node_modules\eslint-config-airbnb\rules\react-a11y.js:
	Configuration for rule "jsx-a11y/anchor-has-content" is invalid:
	Value "[object Object]" should be string.
	Value "[object Object]" should be array.
	Value "[object Object]" should match exactly one schema in oneOf.

Referenced from:<pathToProject>\node_modules\eslint-config-airbnb\index.js
Referenced from: <pathToProject>\.eslintrc

Error: <pathToProject>\node_modules\eslint-config-airbnb\rules\react-a11y.js:
	Configuration for rule "jsx-a11y/anchor-has-content" is invalid:
	Value "[object Object]" should be string.
	Value "[object Object]" should be array.
	Value "[object Object]" should match exactly one schema in oneOf.

Referenced from:<pathToProject>\node_modules\eslint-config-airbnb\index.js
Referenced from: <pathToProject>\.eslintrc
    at validateRuleOptions (<pathToProject>\node_modules\eslint\lib\config\config-validator.js:113:15)
    at Object.keys.forEach.id (<pathToProject>\node_modules\eslint\lib\config\config-validator.js:153:9)
    at Array.forEach (native)
    at validateRules (<pathToProject>\node_modules\eslint\lib\config\config-validator.js:152:30)
    at Object.validate (<pathToProject>\node_modules\eslint\lib\config\config-validator.js:230:5)
    at loadFromDisk (<pathToProject>\node_modules\eslint\lib\config\config-file.js:549:19)
    at load (<pathToProject>\node_modules\eslint\lib\config\config-file.js:592:20)
    at configExtends.reduceRight (<pathToProject>\node_modules\eslint\lib\config\config-file.js:421:36)
    at Array.reduceRight (native)
    at applyExtends (<pathToProject>\node_modules\eslint\lib\config\config-file.js:403:28)
```

node -v 8.1.0
npm -v 5.0.3

What can I do to get rid of this?

**Comment by OlgaKozlova** [comment]
It seems it was a bug of WebStorm. After reopening the project configuration works correct.
