### ISSUE TITLE
Rejection Error: Cannot find module 'fstream'

### ISSUE THREAD

**Issue by ibbatta** [airbnb/javascript#1568]
When I use the code

```bash
(
  export PKG=eslint-config-airbnb;
  npm info "$PKG@latest" peerDependencies --json | command sed 's/[\{\},]//g ; s/: /@/g' | xargs npm install --save-dev "$PKG@latest"
)
```
npm throw me an error:

```bash
Unhandled rejection Error: Cannot find module 'fstream'-session c63a5a4ff43ab050
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/tar.js:15:15)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/pack.js:29:30)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)

npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ibbatta/.npm/_logs/2017-09-25T14_41_47_737Z-debug.log
```

the file log report this:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--save-dev',
1 verbose cli   'eslint-config-airbnb@latest',
1 verbose cli   'eslint@^3.19.0 || ^4.3.0',
1 verbose cli   'eslint-plugin-jsx-a11y@^5.1.1',
1 verbose cli   'eslint-plugin-import@^2.7.0',
1 verbose cli   'eslint-plugin-react@^7.1.0' ]
2 info using npm@5.4.2
3 info using node@v8.5.0
4 verbose npm-session c63a5a4ff43ab050
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 error cb() never called!
8 error This is an error with npm itself. Please report this error at:
9 error <https://github.com/npm/npm/issues>
```

**Comment by ljharb** [comment]
It sounds like a bug in npm 5; if you try npm 4, what happens?

**Comment by ibbatta** [comment]
@ljharb actually not tested with npm 4. I'll check and tell you asap :)

**Comment by ljharb** [comment]
In that case I'd try either reinstalling node, or using nvm to try other node versions.

**Comment by ibbatta** [comment]
Tested, still not work :(

**Comment by ljharb** [comment]
In that case, please file an issue with npm - this isn't something this package caused nor can fix :-(

**Comment by asasaasslxj** [comment]
hello
