### ISSUE TITLE
Multiline comma-dangle on functions?

### ISSUE THREAD

**Issue by sambauers** [airbnb/javascript#1604]
Hi, this rule appears to enforce incorrect syntax for functions. Tell me I'm wrong.

https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/rules/style.js#L47

Example:

```
foo(
  'hello',
  'goodbye',
);
```

That passes listing with airbnb-base, but is broken syntax on execution:

```
);
^
SyntaxError: Unexpected token )
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
```

**Comment by ljharb** [comment]
It is indeed correct as of ES2017. Per the guide, you are expected to be using https://npmjs.com/babel-preset-airbnb or the equivalent; modern web dev without Babel isn't realistic.

**Comment by sambauers** [comment]
Yeah, this isn't web dev (well, not targeted at the browser anyway). I don't have any need to pre-compile, so adding Babel is just a pain. That's OK though. Thanks for the swift reply.

**Comment by ljharb** [comment]
We definitely recommend transpiling for node too :-)

However, you can override the comma-dangle rule to not require commas on functions, if you need to.
