### ISSUE TITLE
npm test failed on windows

### ISSUE THREAD

**Issue by aladdin-add** [airbnb/javascript#1837]
node:  v10.5.0
npm: 6.1.0
os: MINGW64

```bash
$ npm run lint

> airbnb-style@2.0.0 lint C:\repo\javascript
> markdownlint --config linters/.markdownlint.json README.md */README.md

fs.js:126
    throw err;
    ^

Error: ENOENT: no such file or directory, lstat '*/README.md'
    at Object.fs.lstatSync (fs.js:918:3)
    at C:\repo\javascript\node_modules\markdownlint-cli\markdownlint.js:48:20
    at Array.map (<anonymous>)
    at prepareFileList (C:\repo\javascript\node_modules\markdownlint-cli\markdownlint.js:47:17)
    at Object.<anonymous> (C:\repo\javascript\node_modules\markdownlint-cli\markdownlint.js:90:13)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! airbnb-style@2.0.0 lint: `markdownlint --config linters/.markdownlint.json README.md */README.md`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the airbnb-style@2.0.0 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hh_20\AppData\Roaming\npm-cache\_logs\2018-06-24T16_20_55_753Z-debug.log
```

**Comment by ljharb** [comment]
Since i don’t have a windows machine to test on, I’m not sure how to address this.

**Comment by Aladdin-ADD** [comment]
here is my findings:

+ after upgrade `"markdownlint-cli": "^0.3.1"` => `"markdownlint-cli": "^0.10.0"` (refs #1839 ), the error gone.

+ but another error occurs:

```bash
$ npm t

> airbnb-style@2.0.0 pretest C:\repo\javascript
> npm run --silent lint


> airbnb-style@2.0.0 test C:\repo\javascript
> npm run test:config && npm run test:config:base


> airbnb-style@2.0.0 test:config C:\repo\javascript
> cd packages/eslint-config-airbnb && npm test


> eslint-config-airbnb@17.0.0 pretest C:\repo\javascript\packages\eslint-config-airbnb
> npm run --silent lint

fs.js:119
    throw err;
    ^

Error: ENOENT: no such file or directory, lstat '*'
    at Object.lstatSync (fs.js:814:3)
    at C:\repo\javascript\packages\eslint-config-airbnb\node_modules\editorconfig-tools\lib\cli.js:83:16
    at Array.forEach (<anonymous>)
    at C:\repo\javascript\packages\eslint-config-airbnb\node_modules\editorconfig-tools\lib\cli.js:81:25
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (C:\repo\javascript\packages\eslint-config-airbnb\node_modules\editorconfig-tools\lib\cli.js:78:24)
    at Object.<anonymous> (C:\repo\javascript\packages\eslint-config-airbnb\node_modules\editorconfig-tools\lib\cli.js:276:4)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\repo\javascript\packages\eslint-config-airbnb\node_modules\editorconfig-tools\bin\index.js:8:11)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
npm ERR! Test failed.  See above for more details.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! airbnb-style@2.0.0 test:config: `cd packages/eslint-config-airbnb && npm test`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the airbnb-style@2.0.0 test:config script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hh_20\AppData\Roaming\npm-cache\_logs\2018-06-24T18_44_18_517Z-debug.log
npm ERR! Test failed.  See above for more details.
```

**Comment by ljharb** [comment]
it sounds like whatever bugfix markdownlint made for windows, would also need to be applied in editorconfig-tools?

**Comment by ljharb** [comment]
I've switched from `editorconfig-tools` to `eclint`; happy to reopen if that doesn't address this.
