### ISSUE TITLE
Cannot find module 'eslint/lib/util/source-code'

### ISSUE THREAD

**Issue by Boomatang** [airbnb/javascript#2080]
After updating to react-scripts@3.1.1, which included an update to ESLint 6, the eslint-config-airbnb plugin no longer works. See below:

```
ui@0.1.0 lint /home/jfitzpat/code/src/github.com/aerogear/mobile-developer-console
> eslint 'src/**/*.js' 'server/**/*.js'

Error: Failed to load plugin 'import' declared in '.eslintrc.json » plugin:patternfly-react/recommended » eslint-config-airbnb » /home/jfitzpat/code/src/github.com/aerogear/mobile-developer-console/node_modules/eslint-plugin-patternfly-react/node_modules/eslint-config-airbnb-base/index.js » /home/jfitzpat/code/src/github.com/aerogear/mobile-developer-console/node_modules/eslint-plugin-patternfly-react/node_modules/eslint-config-airbnb-base/rules/imports.js': Cannot find module 'eslint/lib/util/source-code'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (/home/jfitzpat/code/src/github.com/aerogear/mobile-developer-console/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/home/jfitzpat/code/src/github.com/aerogear/mobile-developer-console/node_modules/eslint-plugin-import/lib/ExportMap.js:20:19)
    at Module._compile (/home/jfitzpat/code/src/github.com/aerogear/mobile-developer-console/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! ui@0.1.0 lint: `eslint 'src/**/*.js' 'server/**/*.js'`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the ui@0.1.0 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jfitzpat/.npm/_logs/2019-08-26T11_43_47_324Z-debug.log

```

**Comment by Boomatang** [comment]
Thanks for the quick reply. The patternfly-react uses eslint, I meant putting in the eslint version of the stack trace.

But this is not an issue. I had to remove the the `node_modules` folder and `package-lock.json`, after a fresh install it all worked. 

I will close this issue now and thanks again for the quick feedback.
