### ISSUE TITLE
eslint-config-airbnb: error on component destructuring

### ISSUE THREAD

**Issue by South-Paw** [airbnb/javascript#2100]
Hi, hopefully I'm bringing this up in the right place.

I've got a [project](https://github.com/South-Paw/react-vector-maps/tree/3.0.0) using `eslint-config-airbnb` (in the `3.0.0` branch) but I've started getting the following error which wasn't there earlier in the week.

```sh
TypeError: Cannot read property 'type' of undefined
Occurred while linting E:\dev\Github\react-vector-maps\src\VectorMap.js:4
    at checkDestructured (E:\dev\Github\react-vector-maps\node_modules\eslint\lib\rules\no-useless-rename.js:104:43)
    at E:\dev\Github\react-vector-maps\node_modules\eslint\lib\linter\safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (E:\dev\Github\react-vector-maps\node_modules\eslint\lib\linter\safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (E:\dev\Github\react-vector-maps\node_modules\eslint\lib\linter\node-event-generator.js:253:26)
    at NodeEventGenerator.applySelectors (E:\dev\Github\react-vector-maps\node_modules\eslint\lib\linter\node-event-generator.js:282:22)
    at NodeEventGenerator.enterNode (E:\dev\Github\react-vector-maps\node_modules\eslint\lib\linter\node-event-generator.js:296:14)
    at CodePathAnalyzer.enterNode (E:\dev\Github\react-vector-maps\node_modules\eslint\lib\linter\code-path-analysis\code-path-analyzer.js:646:23)
    at E:\dev\Github\react-vector-maps\node_modules\eslint\lib\linter\linter.js:935:32
    at Array.forEach (<anonymous>)
```

The error occurs in any of the files with components [as such](https://github.com/South-Paw/react-vector-maps/blob/3.0.0/src/VectorMap.js#L4) and points to the destructing being the issue?

The issue occured on a CI build earlier and I reproduced it locally as well.

Removing the `eslint-config-airbnb` from the extends of the `.eslintrc.js` removes the error - hence why I thought I'd raise it here.

I fiddled with the project dependencies a bit but nothing seems to make a difference 😟

Any help would really be appreciated

**Comment by ljharb** [comment]
The stack trace says it’s an error with the eslint rule no-useless-rename; presumably if you enabled that rule even without extending airbnb it would still error.

What version of eslint are you using, and what’s your config look like?

**Comment by ljharb** [comment]
Looks like this is https://github.com/eslint/eslint/issues/12335

**Comment by South-Paw** [comment]
@ljharb thanks for pointing me in the right direction - I'll keep track of that issue then 👍
