### ISSUE TITLE
Invalid config for eslint-config-airbnb-base

### ISSUE THREAD

**Issue by jcoyne** [airbnb/javascript#2105]
I believe this configuration is incorrect: https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/rules/imports.js#L256

Because the requirement is at least one item: https://github.com/benmosher/eslint-plugin-import/blob/7ffbf03fc832df41c4e90ffd27fee43de3685224/src/rules/no-unused-modules.js#L280

and I believe it is causing this error:

```
Error: Cannot read config file: /Users/jcoyne85/workspace/ld4p/sinopia_editor/node_modules/eslint-config-airbnb-base/whitespace.js
Error: BaseConfig:
	Configuration for rule "import/no-unused-modules" is invalid:
	Value [] should NOT have fewer than 1 items.

Referenced from: /Users/jcoyne85/workspace/ld4p/sinopia_editor/.eslintrc.js
    at validateRuleOptions (/Users/jcoyne85/workspace/ld4p/sinopia_editor/node_modules/eslint/lib/shared/config-validator.js:138:19)
    at /Users/jcoyne85/workspace/ld4p/sinopia_editor/node_modules/eslint/lib/shared/config-validator.js:193:9
    at Array.forEach (<anonymous>)
    at validateRules (/Users/jcoyne85/workspace/ld4p/sinopia_editor/node_modules/eslint/lib/shared/config-validator.js:190:30)
    at validateConfigArray (/Users/jcoyne85/workspace/ld4p/sinopia_editor/node_modules/eslint/lib/shared/config-validator.js:337:9)
    at CascadingConfigArrayFactory._finalizeConfigArray (/Users/jcoyne85/workspace/ld4p/sinopia_editor/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:392:13)
    at CascadingConfigArrayFactory.getConfigArrayForFile (/Users/jcoyne85/workspace/ld4p/sinopia_editor/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:248:21)
    at CLIEngine.getConfigForFile (/Users/jcoyne85/workspace/ld4p/sinopia_editor/node_modules/eslint/lib/cli-engine/cli-engine.js:916:14)
    at onlyErrorOnRules (/Users/jcoyne85/workspace/ld4p/sinopia_editor/node_modules/eslint-config-airbnb-base/whitespace.js:10:25)
    at Object.<anonymous> (/Users/jcoyne85/workspace/ld4p/sinopia_editor/node_modules/eslint-config-airbnb-base/whitespace.js:30:18)
```

This is using eslint-config-airbnb-base 14.0.0

**Comment by ljharb** [comment]
This is true, but since the rule is disabled, it's not a problem unless you're enabling it and *not* including `ignoreExports`.

However, given that there's no way to un-define that setting, this seems worth fixing.

**Comment by jcoyne** [comment]
The odd thing is that I don't see any reference to `no-unused-modules` in my code, it's only in `node_modules/`

**Comment by ljharb** [comment]
What's your eslintrc?

**Comment by jcoyne** [comment]
https://github.com/LD4P/sinopia_editor/blob/master/.eslintrc.js

**Comment by ljharb** [comment]
That's very strange; none of those configs should be enabling it. I'll see what I can do.

**Comment by Gvozd** [comment]
As can be seen in https://github.com/LD4P/sinopia_editor/issues/1276, this reporuced when used `airbnb-base/whitespace`
This config set all rules(except whitespace rules) to warning level

**Comment by ljharb** [comment]
Thanks, that helps.

**Comment by jcoyne** [comment]
@ljharb Thank you for your work on this problem!

**Comment by portenez** [comment]
Thank you for fixing this, but just double checking.. it hasn't been release, right?

**Comment by ljharb** [comment]
No, it has not yet been released.

**Comment by ljharb** [comment]
It's been released.
