### ISSUE TITLE
eslint-config-airbnb  error

### ISSUE THREAD

**Issue by preethisastry** [airbnb/javascript#2117]
When I run npm run serve, I get the following error - 
Module build failed (from ./node_modules/eslint-loader/index.js):
Error: Cannot find module '@vue/eslint-config-airbnb'
Referenced from: C:\Vue\Projects\build-a-bot\.eslintrc.js
    at ModuleResolver.resolve (C:\Vue\Projects\build-a-bot\node_modules\eslint\lib\util\module-resolver.js:72:19)
    at resolve (C:\Vue\Projects\build-a-bot\node_modules\eslint\lib\config\config-file.js:507:28)
    at load (C:\Vue\Projects\build-a-bot\node_modules\eslint\lib\config\config-file.js:579:26)
    at configExtends.reduceRight (C:\Vue\Projects\build-a-bot\node_modules\eslint\lib\config\config-file.js:453:36)
    at Array.reduceRight (<anonymous>)
    at applyExtends (C:\Vue\Projects\build-a-bot\node_modules\eslint\lib\config\config-file.js:431:26)
    at loadFromDisk (C:\Vue\Projects\build-a-bot\node_modules\eslint\lib\config\config-file.js:551:22)
    at Object.load (C:\Vue\Projects\build-a-bot\node_modules\eslint\lib\config\config-file.js:587:20)
    at Config.getLocalConfigHierarchy (C:\Vue\Projects\build-a-bot\node_modules\eslint\lib\config.js:240:44)
    at Config.getConfigHierarchy (C:\Vue\Projects\build-a-bot\node_modules\eslint\lib\config.js:192:43)
    at Config.getConfigVector (C:\Vue\Projects\build-a-bot\node_modules\eslint\lib\config.js:299:21)
    at Config.getConfig (C:\Vue\Projects\build-a-bot\node_modules\eslint\lib\config.js:342:29)
    at processText (C:\Vue\Projects\build-a-bot\node_modules\eslint\lib\cli-engine.js:181:33)
    at CLIEngine.executeOnText (C:\Vue\Projects\build-a-bot\node_modules\eslint\lib\cli-engine.js:690:40)
    at lint (C:\Vue\Projects\build-a-bot\node_modules\eslint-loader\index.js:278:17)
    at transform (C:\Vue\Projects\build-a-bot\node_modules\eslint-loader\index.js:252:18)

I've manually installed airbnb config using - npm install --save eslint-config-airbnb. 
What am I missing?

**Comment by ljharb** [comment]
`@vue/eslint-config-airbnb` is a different package. What's in your eslint config file?

**Comment by preethisastry** [comment]
Well, I think that's the issue, I have babel.config.js and there is no eslint.config file. But I manually created .eslintrc.js and added the following:
module.exports = {
    root: true,
    'extends': [
        'plugin:vue/essential',
        '@vue/airbnb'
    ],
    rules: {
        "linebreak-style": 0
    }

}

**Comment by ljharb** [comment]
OK, well `@vue/airbnb` would be https://www.npmjs.com/package/@vue/eslint-config-airbnb but that's not this project or this styleguide (and its readme explicitly says it's not for outside use).

Perhaps you mean to extend just "airbnb"? Either way, I'm going to close this, as it's unrelated to this project.

**Comment by preethisastry** [comment]
Sorry, wrong project. I was following a course from Pluralsight. Will post there.

Sent via the Samsung Galaxy Note9, an AT&T 5G Evolution capable smartphone
Get Outlook for Android<https://aka.ms/ghei36>
________________________________
