### ISSUE TITLE
Failed to load config "airbnb-base" to extend from.

### ISSUE THREAD

**Issue by bartekpacia** [airbnb/javascript#2202]
I'm experiencing this after updating all my dependencies to their newest versions, i.e:

my **package.json**
```javascript
"devDependencies": {
    "@typescript-eslint/eslint-plugin": "^2.24.0",
    "@typescript-eslint/parser": "^2.24.0",
    "eslint": "^6.8.0",
    "eslint-config-airbnb-base": "^14.1.0",
    "eslint-config-prettier": "^6.0.1",
    "eslint-plugin-import": "^2.20.1",
    "eslint-plugin-prettier": "^3.1.2",
    "eslint-plugin-promise": "^4.2.1",
    "prettier": "^1.19.1",
    "typescript": "^3.8.3"
  },
```

Output from ESlint in the **output tab**:
```
[Info  - 2:44:15 AM] ESLint server stopped.
[Info  - 2:44:15 AM] ESLint server running in node v12.8.1
[Info  - 2:44:15 AM] ESLint server is running.
[Info  - 2:44:16 AM] ESLint library loaded from: /Users/bartekpacia/dev/node/discover-rudy-functions/functions/node_modules/eslint/lib/api.js
[Error - 2:44:16 AM] ESLint stack trace:
[Error - 2:44:16 AM] Error: Failed to load config "airbnb-base" to extend from.
Referenced from: /Users/bartekpacia/dev/node/discover-rudy-functions/.eslintrc.json
    at configMissingError (/Users/bartekpacia/dev/node/discover-rudy-functions/functions/node_modules/eslint/lib/cli-engine/config-array-factory.js:265:9)
    at ConfigArrayFactory._loadExtendedShareableConfig (/Users/bartekpacia/dev/node/discover-rudy-functions/functions/node_modules/eslint/lib/cli-engine/config-array-factory.js:826:23)
    at ConfigArrayFactory._loadExtends (/Users/bartekpacia/dev/node/discover-rudy-functions/functions/node_modules/eslint/lib/cli-engine/config-array-factory.js:731:25)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/Users/bartekpacia/dev/node/discover-rudy-functions/functions/node_modules/eslint/lib/cli-engine/config-array-factory.js:660:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/Users/bartekpacia/dev/node/discover-rudy-functions/functions/node_modules/eslint/lib/cli-engine/config-array-factory.js:596:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at createConfigArray (/Users/bartekpacia/dev/node/discover-rudy-functions/functions/node_modules/eslint/lib/cli-engine/config-array-factory.js:340:25)
    at ConfigArrayFactory.loadInDirectory (/Users/bartekpacia/dev/node/discover-rudy-functions/functions/node_modules/eslint/lib/cli-engine/config-array-factory.js:433:16)
    at CascadingConfigArrayFactory._loadConfigInAncestors (/Users/bartekpacia/dev/node/discover-rudy-functions/functions/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:328:46)
```

My **eslintrc.json**:
```javascript
"parser": "@typescript-eslint/parser",
  "parserOptions": {
    "ecmaVersion": 2017
  },
  "extends": [
    "airbnb-base",
    "plugin:@typescript-eslint/recommended",
    "prettier/@typescript-eslint",
    "plugin:prettier/recommended",
    "plugin:import/errors"
  ],
  "plugins": ["@typescript-eslint", "prettier", "promise", "import"],
```

I don't have ESLint installed globally, only locally.
Everything seems to be installed correctly, but still, I can't get it to work:c 

any tips?

**Comment by ljharb** [comment]
Certainly it seems like everything's set up correctly.

Are you sure `npm install` is ran, and `npm ls` exits zero?

**Comment by bartekpacia** [comment]
Yes, `npm install` installs everything and exits successfully, `npm ls` - exit code 0

**Comment by ljharb** [comment]
What thing is the “eslint server”? What happens if you just run `npx eslint .` directly on the command line?

**Comment by bartekpacia** [comment]
> What thing is the “eslint server”?

I have no idea, I'm only yet another user of this awesome tool:)

> What happens if you just run npx eslint . directly on the command line?
```
➜  $ npx eslint .
npx: installed 134 in 12.404s
Failed to load config "airbnb-base" to extend from.
Referenced from: /Users/bartekpacia/dev/node/discover-rudy-functions/.eslintrc.json
```

**Comment by ljharb** [comment]
ok, and just to be clear - in that same directory, if you run `npm ls`, what's the output?

**Comment by bartekpacia** [comment]
it prints all installed packages (gist [here](https://gist.github.com/bartekpacia/7ce94e3b4536eefec2e22ca007a74d20))

**Comment by ljharb** [comment]
ok, and the project root is `/Users/bartekpacia/dev/node/discover-rudy-functions/`? that's the dir that has package.json, and from where you're running `npx eslint .`?

**Comment by bartekpacia** [comment]
No, I have `discover-rudy-functions/functions` folder and that's where my `package.json` lives. I ran `npx ...` there.

**Comment by ljharb** [comment]
That's the issue then. Your base eslint config needs to be in the same folder as your package.json, node_modules, and where you run the eslint command.

Currently your eslint config is one level *higher* than package.json, which means that there's nothing installed for it to find.

**Comment by badis** [comment]
@bartekpacia I had this same issue and this SO answer fixed it for me: https://stackoverflow.com/a/47178406/3756168

**Comment by badis** [comment]
I had the same issue and this fixed it!

```
npm install -g install-peerdeps
install-peerdeps --dev eslint-config-airbnb
```

**Comment by idadrusdiana** [comment]
> Thanks for response:)
> Yes, `npm install` installs everything and exits successfully, `npm ls` - exit code 0

ok thanks

**Comment by Evgeny-Mufteev** [comment]
install-peerdeps --dev eslint-config-airbnb-base Помогло, спасибо
