### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by toxic-johann** [airbnb/javascript#2226]
Meet this error when I run` eslint-config-airbnb` and the `eslint-plugin-import` together.

```
TypeError: Cannot read property 'name' of undefined
Occurred while linting /Users/toxic/Documents/workspace/tubi/www/src/common/components/uilib/ottLib.js:1
    at astNode.specifiers.forEach.specifier (/Users/toxic/Documents/workspace/tubi/www/node_modules/eslint-plugin-import/lib/rules/no-unused-modules.js:703:40)
    at Array.forEach (<anonymous>)
    at node.body.forEach.astNode (/Users/toxic/Documents/workspace/tubi/www/node_modules/eslint-plugin-import/lib/rules/no-unused-modules.js:698:32)
    at Array.forEach (<anonymous>)
    at updateImportUsage (/Users/toxic/Documents/workspace/tubi/www/node_modules/eslint-plugin-import/lib/rules/no-unused-modules.js:691:17)
    at Program:exit (/Users/toxic/Documents/workspace/tubi/www/node_modules/eslint-plugin-import/lib/rules/no-unused-modules.js:918:9)
    at listeners.(anonymous function).forEach.listener (/Users/toxic/Documents/workspace/tubi/www/node_modules/eslint/lib/linter/safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/toxic/Documents/workspace/tubi/www/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/toxic/Documents/workspace/tubi/www/node_modules/eslint/lib/linter/node-event-generator.js:254:26)
```

I build a simple project for you to reproduce the error. You can take a look here. https://github.com/toxic-johann/eslint-plugin-import-bug

This error will crash the winter. It will appear when a file has no import but just export like this one.

```
export AboutPage from './About';
```

**Comment by ljharb** [comment]
That's not valid syntax - it's `export { AboutPage } from './About'`, or `export { default } from './About'`, or `export * from './About'`, or `export * as foo from './About'`.

Perhaps you're referring to the stage 1 proposal syntax, https://github.com/tc39/proposal-export-default-from ?

**Comment by toxic-johann** [comment]
Yes. You are right. Thanks for the clarification. I will try to see if there are any better options for this or otherwise I will change the code.
