### ISSUE TITLE
cannot find module 'typescript' after upgrading to eslint@7.2.0

### ISSUE THREAD

**Issue by HualiangLI** [airbnb/javascript#2239]
We got an error as following after upgrading `eslint` to `v7.2.0` which is released 2 days ago:
```
ERROR in ./src/main.js
Module build failed: Error: Cannot find module 'typescript'
Referenced from: /operation-yh-fi-share/fis-mengine-ui/node_modules/eslint-config-airbnb-base/index.js
Referenced from: /operation-yh-fi-share/fis-mengine-ui/.eslintrc.js
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/operation-yh-fi-share/fis-mengine-ui/node_modules/eslint-plugin-import/lib/ExportMap.js:46:19)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/operation-yh-fi-share/fis-mengine-ui/node_modules/eslint-plugin-import/lib/rules/named.js:7:18)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
 @ multi babel-polyfill ./src/main.js
```

And after adding and installing `typescript`, everything works good.

**Comment by ljharb** [comment]
This issue doesn't belong on this repo; and it's already been filed and fixed [here](https://github.com/benmosher/eslint-plugin-import/issues/1805), and will shortly be released.
