### ISSUE TITLE
Error: Failed to load config "prettier" to extend from.

### ISSUE THREAD

**Issue by yubaoquan** [airbnb/javascript#2286]
```
[Error - 下午12:51:12] ESLint stack trace:
[Error - 下午12:51:12] Error: Failed to load config "prettier" to extend from.
Referenced from: D:\rs-test\minigrep\node_modules\eslint-config-airbnb-typescript\.eslintrc.js
    at configInvalidError (D:\rs-test\minigrep\node_modules\eslint\lib\cli-engine\config-array-factory.js:295:9)
    at ConfigArrayFactory._loadExtendedShareableConfig (D:\rs-test\minigrep\node_modules\eslint\lib\cli-engine\config-array-factory.js:876:23)
    at ConfigArrayFactory._loadExtends (D:\rs-test\minigrep\node_modules\eslint\lib\cli-engine\config-array-factory.js:776:25)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (D:\rs-test\minigrep\node_modules\eslint\lib\cli-engine\config-array-factory.js:715:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (D:\rs-test\minigrep\node_modules\eslint\lib\cli-engine\config-array-factory.js:660:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at ConfigArrayFactory.loadInDirectory (D:\rs-test\minigrep\node_modules\eslint\lib\cli-engine\config-array-factory.js:508:28)
    at CascadingConfigArrayFactory._loadConfigInAncestors (D:\rs-test\minigrep\node_modules\eslint\lib\cli-engine\cascading-config-array-factory.js:367:46)
    at CascadingConfigArrayFactory.getConfigArrayForFile (D:\rs-test\minigrep\node_modules\eslint\lib\cli-engine\cascading-config-array-factory.js:288:18)

```

version: 
    "eslint-config-airbnb-typescript": "10.0.0",

**Comment by ljharb** [comment]
That package is not owned by Airbnb nor is maintained in this repo.

**Comment by yubaoquan** [comment]
But this package requires prettier. Should you add it to dependencies?

**Comment by ljharb** [comment]
@yubaoquan you'd have to ask that package's maintainers. This repo only has `eslint-config-airbnb` and `eslint-config-airbnb-base`.

**Comment by yubaoquan** [comment]
> @yubaoquan you'd have to ask that package's maintainers. This repo only has `eslint-config-airbnb` and `eslint-config-airbnb-base`.

My bad. Sorry
