### ISSUE TITLE
eslint-config-airbnb-base: "Configuration for rule "prefer-regex-literals" is invalid:"

### ISSUE THREAD

**Issue by sambunting** [airbnb/javascript#2521]
I'm not 100% positive if this is the right place to be asking this - but I'm having some issues when it comes to running ESLint.

    eslint .
    Error: .eslintrc.js » eslint-config-airbnb » /Users/sam.bunting/Desktop/project/node_modules/eslint-config-airbnb-base/index.js » /Users/sam.bunting/Desktop/project/node_modules/eslint-config-airbnb-base/rules/best-practices.js:
            Configuration for rule "prefer-regex-literals" is invalid:
            Value [{"disallowRedundantWrapping":true}] should NOT have more than 0 items.

        at validateRuleOptions (/usr/local/lib/node_modules/eslint/lib/shared/config-validator.js:138:19)
        at /usr/local/lib/node_modules/eslint/lib/shared/config-validator.js:193:9
        at Array.forEach (<anonymous>)
        at validateRules (/usr/local/lib/node_modules/eslint/lib/shared/config-validator.js:190:30)
        at validateConfigArray (/usr/local/lib/node_modules/eslint/lib/shared/config-validator.js:337:9)
        at CascadingConfigArrayFactory._finalizeConfigArray (/usr/local/lib/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:417:13)
        at CascadingConfigArrayFactory.getConfigArrayForFile (/usr/local/lib/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:271:21)
        at FileEnumerator._iterateFilesRecursive (/usr/local/lib/node_modules/eslint/lib/cli-engine/file-enumerator.js:396:49)
        at _iterateFilesRecursive.next (<anonymous>)
        at FileEnumerator.iterateFiles (/usr/local/lib/node_modules/eslint/lib/cli-engine/file-enumerator.js:251:49)

I haven't set any project specific rules - so it must be something set in `eslint-config-airbnb-base` maybe?

Dependency wise - I'm using these eslint related packages:

    "eslint": "^7.32.0",
    "eslint-config-airbnb": "^19.0.1",
    "eslint-plugin-import": "^2.25.3",
    "eslint-plugin-jsx-a11y": "^6.5.1",
    "eslint-plugin-react": "^7.27.1",
    "eslint-plugin-react-hooks": "^4.3.0",

**Comment by sambunting** [comment]
So uh - You know how ESLint says to not install it globally? Welp. Turns out I had it installed globally 🙃 

So - with that, the steps I've taken to fix this issue is:

1. Uninstall ESLint globally
   `npm uninstall -g eslint`
2. Add a "lint" script to my `package.json` file:
   `npm set-script lint "eslint ."`
3. Run ESLint through NPM:
   `npm run lint`

With that - I don't get any errors!

Not too sure entirely why it threw the error, I guess the version I had installed globally was an old version, or causing conflicts with the locally installed packages? But I'm closing this issue since it's more to do with user error rather than an issue with the package itself.

**Comment by ljharb** [comment]
It was an old version, yes.

**Comment by sstadt** [comment]
I ran into this issue when setting up a new project with a fresh workflow, seems backing down a major version for the airbnb and airbnb-base config solved the problem

```
    "eslint-config-airbnb": "^18.0.1",
    "eslint-config-airbnb-base": "^14.0.0",
```

**Comment by ljharb** [comment]
@sstadt that shouldn't be necessary; you may need to be on the latest of those 2 as well as eslint.

**Comment by ljharb** [comment]
That strongly implies something else is wrong, then, since all our tests pass and we check npm ls in CI, unlike most projects.

Can you share the relevant dev deps from package.json, and the error message, and what command you ran to get it?
