### ISSUE TITLE
How to report such errors about "prefer-regex-literals" and how to solve them

### ISSUE THREAD

**Issue by Stephon-Xuan** [airbnb/javascript#2552]
![企业微信截图_16457786035893](https://user-images.githubusercontent.com/51940177/155685561-4c8012ac-72cc-4e3d-b7ac-158e0882a83b.png)

"eslint-config-airbnb": "^19.0.4",

eslint-config-airbnb » D:\project-todo\wheels\wk-lint-config\node_modules\eslint-config-airbnb-base\index.js » D:\project-todo\wheels\wk-lint-config\node_modules\eslint-config-airbnb-base\rules\best-practices.js: 	Configuration for rule "prefer-regex-literals" is invalid: 	Value [{"disallowRedundantWrapping":true}] should NOT have more than 0 items.

**Comment by ljharb** [comment]
What version of eslint are you using? Does `npm ls` exit zero?

**Comment by Stephon-Xuan** [comment]
"eslint": "^8.4.1",
"eslint-config-airbnb": "^19.0.4",
"eslint-config-airbnb-base": "^15.0.0",
"eslint-config-airbnb-typescript": "^16.1.0",

**Comment by Stephon-Xuan** [comment]
"eslint": "^8.4.1",
"eslint-config-airbnb": "^19.0.4",
"eslint-config-airbnb-base": "^15.0.0",
"eslint-config-airbnb-typescript": "^16.1.0",

**Comment by ljharb** [comment]
Closing pending more info.

**Comment by itayganor** [comment]
It happens to me too.

```
    "@typescript-eslint/eslint-plugin": "^5.37.0",
    "@typescript-eslint/parser": "^5.37.0",
    "eslint": "8.22.0",
    "eslint-config-airbnb": "^19.0.4",
    "eslint-config-airbnb-base": "^15.0.0",
    "eslint-plugin-import": "^2.26.0",
    "eslint-plugin-jsx-a11y": "^6.6.1",
    "eslint-plugin-react": "^7.31.8",
    "eslint-plugin-react-hooks": "^4.6.0",
```

**Comment by tnagorra** [comment]
I can also confirm this issue.

eslint version: v8.44.0
node version: v18.16.0
eslint-config-airbnb version: 19.0.4

```
src/index.ts → build/cjs...
[!] (plugin eslint) Error: .eslintrc.cjs » eslint-config-airbnb » /home/snowman/Projects/toggle/internal/toggle-request/node_modules/eslint-config-airbnb-base/index.js » /home/snowman/Projects/toggle/internal/toggle-request/node_modules/eslint-config-airbnb-base/rules/best-practices.js:
	Configuration for rule "prefer-regex-literals" is invalid:
	Value [{"disallowRedundantWrapping":true}] should NOT have more than 0 items.

src/index.ts
    at validateRuleOptions (/home/snowman/Projects/toggle/internal/toggle-request/node_modules/rollup-plugin-eslint/node_modules/eslint/lib/shared/config-validator.js:138:19)
    at /home/snowman/Projects/toggle/internal/toggle-request/node_modules/rollup-plugin-eslint/node_modules/eslint/lib/shared/config-validator.js:193:9
    at Array.forEach (<anonymous>)
    at validateRules (/home/snowman/Projects/toggle/internal/toggle-request/node_modules/rollup-plugin-eslint/node_modules/eslint/lib/shared/config-validator.js:190:30)
    at validateConfigArray (/home/snowman/Projects/toggle/internal/toggle-request/node_modules/rollup-plugin-eslint/node_modules/eslint/lib/shared/config-validator.js:337:9)
    at CascadingConfigArrayFactory._finalizeConfigArray (/home/snowman/Projects/toggle/internal/toggle-request/node_modules/rollup-plugin-eslint/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:417:13)
    at CascadingConfigArrayFactory.getConfigArrayForFile (/home/snowman/Projects/toggle/internal/toggle-request/node_modules/rollup-plugin-eslint/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:271:21)
    at CLIEngine.isPathIgnored (/home/snowman/Projects/toggle/internal/toggle-request/node_modules/rollup-plugin-eslint/node_modules/eslint/lib/cli-engine/cli-engine.js:951:18)
    at Object.transform (/home/snowman/Projects/toggle/internal/toggle-request/node_modules/rollup-plugin-eslint/index.js:36:15)
    at /home/snowman/Projects/toggle/internal/toggle-request/node_modules/rollup/dist/shared/rollup.js:25151:40
```
