### ISSUE TITLE
Error with "airbnb/whitespace" in extends: Configuration for rule "class-methods-use-this" is invalid

### ISSUE THREAD

**Issue by tif-calin** [airbnb/javascript#2576]
Hello I'm having an issue with adding "airbnb/whitespace" to extends. Everything works fine without it, but not matter what order I put things in, "airbnb/whitespace" seems to break my live eslint server. All of the relevant packages are on the latest version.

The weird thing is that we can successfully run linting from the CLI but the live server for VS Code does not start up. Here is the error we are getting in our VS Code terminal:
```
(node:41843) UnhandledPromiseRejectionWarning: Error: .eslintrc.json » eslint-config-airbnb/whitespace:
	Configuration for rule "class-methods-use-this" is invalid:
	Value {"exceptMethods":["render","getInitialState","getDefaultProps","getChildContext","componentWillMount","UNSAFE_componentWillMount","componentDidMount","componentWillReceiveProps","UNSAFE_componentWillReceiveProps","shouldComponentUpdate","componentWillUpdate","UNSAFE_componentWillUpdate","componentDidUpdate","componentWillUnmount","componentDidCatch","getSnapshotBeforeUpdate"],"enforceForClassFields":true} should NOT have additional properties.

    at ConfigValidator.validateRuleOptions ([REDACTED]/frontend/node_modules/@eslint/eslintrc/lib/shared/config-validator.js:144:23)
    at [REDACTED]/frontend/node_modules/@eslint/eslintrc/lib/shared/config-validator.js:199:18
    at Array.forEach (<anonymous>)
    at ConfigValidator.validateRules ([REDACTED]/frontend/node_modules/@eslint/eslintrc/lib/shared/config-validator.js:196:34)
    at ConfigValidator.validateConfigArray ([REDACTED]/frontend/node_modules/@eslint/eslintrc/lib/shared/config-validator.js:322:18)
    at CascadingConfigArrayFactory._finalizeConfigArray ([REDACTED]/frontend/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:493:23)
    at CascadingConfigArrayFactory.getConfigArrayForFile ([REDACTED]/frontend/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:299:21)
    at CLIEngine.getConfigForFile ([REDACTED]/frontend/node_modules/eslint/lib/cli-engine/cli-engine.js:953:14)
    at A.calculateConfigForFile (/Users/culi/.vscode/extensions/dbaeumer.vscode-eslint-2.2.2/server/out/eslintServer.js:1:167786)
    at /Users/culi/.vscode/extensions/dbaeumer.vscode-eslint-2.2.2/server/out/eslintServer.js:1:176344

```

<details>

<summary>
My `.eslintrc.json`

</summary>

```json
{
  "env": {
    "browser": true,
    "es2021": true,
    "jest": true
  },
  "extends": [
    "airbnb",
    "airbnb/hooks",
    "airbnb/whitespace",
    "plugin:import/typescript",
    "prettier",
    "plugin:prettier/recommended"
  ],
  "ignorePatterns": [
    "build/", 
    "node_modules/", 
    "dist/",
    "schemaQuery.js",
    "src/apollo/fragments/*"
  ],
  "overrides": [
    {
      "files": [
        "*.ts",
        "*.tsx"
      ],
      "extends": [
        "prettier",
        "plugin:@typescript-eslint/recommended"
      ]
    },
    {
      "files": [
        "src/components/Document/templates/**"
      ],
      "rules": {
        "import/no-unused-modules": "off"
      }
    }
  ],
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "ecmaFeatures": {
      "jsx": true
    },
    "ecmaVersion": "latest",
    "sourceType": "module"
  },
  "plugins": [
    "react",
    "@typescript-eslint",
    "prettier",
    "@regru/eslint-plugin-prefer-early-return"
  ],
  "rules": {
    "@typescript-eslint/ban-ts-comment": [
      2,
      {
        "ts-ignore": false,
        "minimumDescriptionLength": 10
      }
    ],
    "no-use-before-define": "off",
    "@typescript-eslint/no-use-before-define": [
      1
    ],
    "no-useless-constructor": "off",
    "@typescript-eslint/no-useless-constructor": 0,
    "react/prop-types": 1,
    "react/forbid-prop-types": 1,
    "react/jsx-props-no-spreading": 1,
    "react/require-default-props": 0,
    "no-underscore-dangle": [
      "error",
      {
        "allow": [
          "__typename",
          "_id"
        ]
      }
    ],
    "react/jsx-filename-extension": [
      1,
      {
        "extensions": [
          ".js",
          ".jsx",
          ".tsx"
        ]
      }
    ],
    "react/function-component-definition": 0,
    "@regru/prefer-early-return/prefer-early-return": 1,
    "prefer-arrow-callback": 1,
    "arrow-body-style": [
      1,
      "as-needed"
    ],
    "import/order": [
      "error",
      {
        "newlines-between": "never"
      }
    ],
    "react/no-unescaped-entities": 0,
    "import/extensions": [
      "error",
      "ignorePackages",
      {
        "js": "never",
        "jsx": "never",
        "ts": "never",
        "tsx": "never"
      }
    ],
    "import/no-unused-modules": [
      "error",
      {
        "unusedExports": true,
        "missingExports": false
      }
    ],
    "no-console": [
      1
    ],
    "no-shadow": [
      0
    ]
  },
  "settings": {
    "react": {
      "pragma": "React",
      "version": "detect"
    },
    "import/resolver": {
      "typescript": {},
      "node": {
        "paths": ["frontend/src"]
      }
    }
  }
}
```

</details>

<details>

<summary> My `devDependencies`

</summary>

```json
  "devDependencies": {
    "@prettier/plugin-ruby": "^0.20.1",
    "@regru/eslint-plugin-prefer-early-return": "^1.0.0",
    "@typescript-eslint/eslint-plugin": "^5.15.0",
    "@typescript-eslint/parser": "^5.15.0",
    "eslint": "^8.11.0",
    "eslint-config-airbnb": "^19.0.4",
    "eslint-config-prettier": "^8.5.0",
    "eslint-import-resolver-typescript": "^2.5.0",
    "eslint-plugin-import": "^2.25.4",
    "eslint-plugin-jsx-a11y": "^6.5.1",
    "eslint-plugin-prettier": "^4.0.0",
    "eslint-plugin-react": "^7.29.4",
    "eslint-plugin-react-hooks": "^4.3.0",
    "prettier": "^2.5.1"
  }
```

</details>

This is on an (old) Create React App. I don't recall my specific setup but I've gotten this `should NOT have additional properties` error before with another rule.

**Comment by tif-calin** [comment]
Wow ok I think I know what the issue is, but I don't know the solution. Important context is that this is a monorepo with a /frontend/ repo inside of it which contains a create-react-app project.

Previously all the eslint stuff was inside of the CRA, but the live server wasn't working and looking stuff up online suggested that the solution would be to move it to the parent repo. This worked for everything except "airbnb/whitespace" seems to break it

Because the CRA comes with its own installation of ESLint, the ESLint server seems to be looking at the `config-validator.js` of the frontend's `node_modules` instead of the one in the parent repo.

I will try seeing if I can update the CRA's 'config-validator' somehow...

**Comment by tif-calin** [comment]
Ok yeah the solution was to [use yarn resolutions](https://darekkay.com/blog/create-react-app-eslint/) to force CRA to use an updated version of eslint. I don't know of a way to make the ESLint server avoid using the @eslint inside of the child repo instead of the one in the parent repo

Regardless it doesn't seem to have been any issue with the airbnb plugin

**Comment by ljharb** [comment]
Indeed, when using CRA, you basically can't do anything useful without ejecting, including customizing the eslint config.
