### ISSUE TITLE
YAMLException: Cannot read config file

### ISSUE THREAD

**Issue by dsernst** [airbnb/javascript#696]
Trying to install the eslint shared config from here: https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb

As soon as I add `extends: 'airbnb/base'` to my `.eslintrc`, I see this error:

```
YAMLException: Cannot read config file: /Users/dsernst/Documents/example_repo/node_modules/eslint-config-airbnb/rules/es6.js
Error: end of the stream or a document separator is expected at line 2, column 8:
      'env': {
           ^
Referenced from: airbnb/base
Referenced from: /Users/dsernst/Documents/example_repo/.eslintrc
    at generateError (/Users/dsernst/.nvm/versions/node/v4.1.1/lib/node_modules/eslint/node_modules/js-yaml/lib/js-yaml/loader.js:160:10)
    at throwError (/Users/dsernst/.nvm/versions/node/v4.1.1/lib/node_modules/eslint/node_modules/js-yaml/lib/js-yaml/loader.js:166:9)
    at readDocument (/Users/dsernst/.nvm/versions/node/v4.1.1/lib/node_modules/eslint/node_modules/js-yaml/lib/js-yaml/loader.js:1498:5)
    at loadDocuments (/Users/dsernst/.nvm/versions/node/v4.1.1/lib/node_modules/eslint/node_modules/js-yaml/lib/js-yaml/loader.js:1538:5)
    at load (/Users/dsernst/.nvm/versions/node/v4.1.1/lib/node_modules/eslint/node_modules/js-yaml/lib/js-yaml/loader.js:1555:19)
    at Object.safeLoad (/Users/dsernst/.nvm/versions/node/v4.1.1/lib/node_modules/eslint/node_modules/js-yaml/lib/js-yaml/loader.js:1573:10)
    at readConfigFromFile (/Users/dsernst/.nvm/versions/node/v4.1.1/lib/node_modules/eslint/lib/config.js:121:27)
    at loadConfig (/Users/dsernst/.nvm/versions/node/v4.1.1/lib/node_modules/eslint/lib/config.js:172:22)
    at /Users/dsernst/.nvm/versions/node/v4.1.1/lib/node_modules/eslint/lib/config.js:203:46
    at Array.reduceRight (native)
```

I'm following the standard instructions to install these eslint rules. I've gotten this to work in the past... I even have another project open where I've been using these shared configs just fine for months.

Tried uninstall and reinstalling, did not help.

I see this relevant issue: https://github.com/eslint/eslint/issues/1443 . Same symptoms, but I am on the latest OS X. Using spaces consistently, no tabs sneaking in anywhere.

Seems very strange. Any idea what's going on? Is anyone else seeing this?

**Comment by IvanDimanov** [comment]
Faced the same problem on Ubuntu 14.04 with
```
$ npm version
{ node_test: '1.0.0',
  npm: '3.3.12',
  ares: '1.10.1-DEV',
  http_parser: '2.6.0',
  icu: '56.1',
  modules: '47',
  node: '5.5.0',
  openssl: '1.0.2e',
  uv: '1.8.0',
  v8: '4.6.85.31',
  zlib: '1.2.8' }

```

```
$ npm ls eslint-config-airbnb eslint-plugin-react eslint
node_test@1.0.0 /home... /node_test
├── eslint@1.2.1  extraneous
├── eslint-config-airbnb@4.0.0  extraneous
└── eslint-plugin-react@3.16.1  extraneous

```

**Comment by arisAlexis** [comment]
+1

**Comment by IvanDimanov** [comment]
I found that I have the problem using eslint@1.2.1 but no problem with eslint@1.10.3

**Comment by ljharb** [comment]
You should be using the latest eslint - our package.json requires that i believe.

**Comment by Draekane** [comment]
I had this issue on eslint@1.10.3 and then after reading the above about requiring the latest, I upped it to the newest, which was eslint@2.2.0  I am getting almost the same error, but mine is throwing the error on line 2 of the eslint-config-airbnb\rules\react.js ''plugins':

**Comment by bengotow** [comment]
I'm having this issue on a fresh install (eslint-config-airbnb@6.0.2 and eslint@2.20):

```
/usr/local/lib/node_modules/eslint/lib/config/config-file.js:143
        throw e;
              ^
YAMLException: duplicated mapping key at line 45, column 30:
    			"beforeLineComment": false,
                                 ^
    at generateError (/usr/local/lib/node_modules/eslint/node_modules/js-yaml/lib/js-yaml/loader.js:162:10)
    at throwError (/usr/local/lib/node_modules/eslint/node_modules/js-yaml/lib/js-yaml/loader.js:168:9)
    at storeMappingPair (/usr/local/lib/node_modules/eslint/node_modules/js-yaml/lib/js-yaml/loader.js:305:7)
    at readFlowCollection (/usr/local/lib/node_modules/eslint/node_modules/js-yaml/lib/js-yaml/loader.js:720:7)
    at composeNode (/usr/local/lib/node_modules/eslint/node_modules/js-yaml/lib/js-yaml/loader.js:1327:11)
    at readFlowCollection (/usr/local/lib/node_modules/eslint/node_modules/js-yaml/lib/js-yaml/loader.js:704:5)
    at composeNode (/usr/local/lib/node_modules/eslint/node_modules/js-yaml/lib/js-yaml/loader.js:1327:11)
    at readFlowCollection (/usr/local/lib/node_modules/eslint/node_modules/js-yaml/lib/js-yaml/loader.js:715:7)
    at composeNode (/usr/local/lib/node_modules/eslint/node_modules/js-yaml/lib/js-yaml/loader.js:1327:11)
    at readFlowCollection (/usr/local/lib/node_modules/eslint/node_modules/js-yaml/lib/js-yaml/loader.js:715:7)

```

**Comment by ljharb** [comment]
@bengotow we don't have `beforeLineComment` anywhere in our code - what's your config file look like?

**Comment by bengotow** [comment]
Hi @ljharb — thanks for the quick reply. Upon further digging it looks like the issue might have been within `eslint` itself, since the airbnb code isn't referenced at all in the stack trace. Super strange. Sorry for the hassle!

**Comment by ljharb** [comment]
I'm going to close this for now, then - please feel free to link it to an eslint issue if one is filed
