### ISSUE TITLE
Configuration for rule "no-labels" is invalid

### ISSUE THREAD

**Issue by gnicol-bzh** [airbnb/javascript#779]
Hello,

I created a new `.eslintrc` and copy/paste in it:
```json
{
  "extends": "airbnb"
}
```
Then I've installed packages as specified in [airbnb doc](https://github.com/airbnb/javascript/tree/master/linters). 

When I run eslint, I have the error:
```bat
D:\_PROJECTPATH_>gulp eslint
[12:37:06] Using gulpfile D:\_PROJECTPATH_\gulpfile.js
[12:37:06] Starting 'eslint'...
D:\_PROJECTPATH_\node_modules\gulp-eslint\node_modules\eslint\lib\config\config-file.js:332
            throw e;
                  ^
Error: D:\_PROJECTPATH_\node_modules\eslint-config-airbnb\rules\best-practices.js:
        Configuration for rule "no-labels" is invalid:
        Value "2,[object Object]" has more items than allowed.

Referenced from: D:\_PROJECTPATH_\node_modules\eslint-config-airbnb\legacy.js
Referenced from: D:\_PROJECTPATH_\node_modules\eslint-config-airbnb\base.js
Referenced from: airbnb
Referenced from: D:\_PROJECTPATH_\.eslintrc
    at validateRuleOptions (D:\_PROJECTPATH_\node_modules\gulp-eslint\node_modules\eslint\lib\config\config-validator.js:102:15)
    at D:\_PROJECTPATH_\node_modules\gulp-eslint\node_modules\eslint\lib\config\config-validator.js:148:13
    at Array.forEach (native)
    at Object.validate (D:\_PROJECTPATH_\node_modules\gulp-eslint\node_modules\eslint\lib\config\config-validator.js:147:35)
    at load (D:\_PROJECTPATH_\node_modules\gulp-eslint\node_modules\eslint\lib\config\config-file.js:390:19)
    at D:\_PROJECTPATH_\node_modules\gulp-eslint\node_modules\eslint\lib\config\config-file.js:326:36
    at Array.reduceRight (native)
    at applyExtends (D:\_PROJECTPATH_\node_modules\gulp-eslint\node_modules\eslint\lib\config\config-file.js:309:28)
    at load (D:\_PROJECTPATH_\node_modules\gulp-eslint\node_modules\eslint\lib\config\config-file.js:395:22)
    at D:\_PROJECTPATH_\node_modules\gulp-eslint\node_modules\eslint\lib\config\config-file.js:326:36
```

Someone else has the same problem [here](https://github.com/Swiip/generator-gulp-angular/issues/1022)

**Comment by ljharb** [comment]
This might be an issue with `gulp-eslint` - what's your `npm ls` look like?

**Comment by benjeffery** [comment]
I'm also getting this error using plain eslint. Commenting out the 'no-labels' line from rules/best-practices.js suppresses the error as a temp workaround.

**Comment by ljharb** [comment]
Which version of eslint?

**Comment by benjeffery** [comment]
Gah, I thought I was on the latest but erroneously had 1.10.3.... works on 2.3.0. Thanks.

**Comment by ljharb** [comment]
np, glad we figured it out!

**Comment by andreyvolokitin** [comment]
Same error:
```
/Users/andreyvolokitin/webdev/project stubs/main stub/node_modules/gulp-eslint/node_modules/eslint/lib/config/config-file.js:332
            throw e;
            ^

Error: /Users/andreyvolokitin/webdev/project stubs/main stub/node_modules/eslint-config-airbnb/rules/best-practices.js:
        Configuration for rule "no-labels" is invalid:
        Value "2,[object Object]" has more items than allowed.
```

I have eslint 2.7.0 installed. And also commenting out this line from ```/node_modules/eslint-config-airbnb/rules/best-practices.js``` removes this error:

```'no-labels': [2, { 'allowLoop': false, 'allowSwitch': false }]```

**Comment by ljharb** [comment]
@andreyvolokitin do you have eslint 2.7.0 installed locally or globally? Does `npm ls -g --depth=0` include a version of eslint that's different than `npm ls --depth=0`?

**Comment by andreyvolokitin** [comment]
@ljharb yes, I have different versions — 2.7.0 locally, and 2.5.3 globally, but also I had gulp-eslint 1.0.0 which I updated to 2.0.0 and then error disappeared
