### ISSUE TITLE
eslint-config-airbnb-base looks in global

### ISSUE THREAD

**Issue by brendanvinson** [airbnb/javascript#858]
I just tried installing eslint-config-airbnb-base, but when I try to run it, it looks for a global install instead of in my project.

```shell
Cannot find module 'eslint-config-airbnb-base' from '/usr/local/lib/node_modules'
Referenced from: /Users/brendanvinson/Projects/<project>/.eslintrc.yml
Error: Cannot find module 'eslint-config-airbnb-base' from '/usr/local/lib/node_modules'
Referenced from: /Users/brendanvinson/Projects/<project>/.eslintrc.yml
    at Function.module.exports [as sync] (/usr/local/lib/node_modules/eslint/node_modules/resolve/lib/sync.js:33:11)
    at resolve (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:442:38)
    at load (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:462:24)
    at /usr/local/lib/node_modules/eslint/lib/config/config-file.js:369:36
    at Array.reduceRight (native)
    at applyExtends (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:346:28)
    at Object.load (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:491:22)
    at loadConfig (/usr/local/lib/node_modules/eslint/lib/config.js:67:33)
    at getLocalConfig (/usr/local/lib/node_modules/eslint/lib/config.js:129:23)
    at Config.getConfig (/usr/local/lib/node_modules/eslint/lib/config.js:230:22)
```

Instructions to install imply that this should run locally to the project path.

**Comment by ljharb** [comment]
Everything should definitely be installed globally. However, it looks like you're running `eslint` bare, ie, the globally installed one - as opposed to `./node_modules/.bin/eslint`, the locally installed one.

**Comment by brendanvinson** [comment]
I removed the globally installed versions and then ran `npm run lint`:
```json
"scripts": {
    "lint": "eslint src/ test/ --quiet"
  },
```
and received this error:
```shell
> eslint src/ test/ --quiet

module.js:440
    throw err;
    ^

Error: Cannot find module 'core-util-is'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/brendanvinson/Projects/<project>/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_readable.js:46:12)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
```

**Comment by ljharb** [comment]
what does `npm ls` output? It seems like perhaps your `node_modules` is messed up - try `rm -rf node_modules && npm install`?

**Comment by brendanvinson** [comment]
looks like that solved it. thanks!
