### ISSUE TITLE
Error: Cannot read config package: eslint-config-airbnb

### ISSUE THREAD

**Issue by alanrsoares** [airbnb/javascript#871]
I'm using node 6 on OSX El Capitan
```
Error: Cannot find module 'eslint-config-airbnb'
Referenced from: ~/dev/{project-name}/.eslintrc
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at loadPackage (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:168:16)
    at loadConfigFile (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:212:18)
    at load (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:385:18)
    at /usr/local/lib/node_modules/eslint/lib/config/config-file.js:326:36
    at Array.reduceRight (native)
    at applyExtends (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:309:28)
```

**Comment by ljharb** [comment]
Do you have `eslint-config-airbnb` installed in `~/dev/{project-name}/node_modules`?

**Comment by ljharb** [comment]
Also, what version of `eslint` are you using? What's `npm ls` print out?

**Comment by alanrsoares** [comment]
I do have it in `node_modules`
```
"eslint": "^2.9.0",
"eslint-config-airbnb": "^9.0.1",
"eslint-plugin-import": "^1.7.0",
"eslint-plugin-jsx-a11y": "^1.2.0",
"eslint-plugin-react": "^5.0.1",
```

**Comment by ljharb** [comment]
and how are you invoking `eslint`? Are you doing it bare on the command line (such that `which eslint` doesn't point to the local one), or are you using an `npm run-script`?

**Comment by alanrsoares** [comment]
Damn, I was calling it from the command line, that's why it wasn't resolving the module.
Thanks heaps dude.
