### ISSUE TITLE
Crash for react/display-name rule

### ISSUE THREAD

**Issue by AlexMost** [airbnb/javascript#892]
Something wrong with 'react/display-name' rule

```
node_modules/.bin/eslint uaprom/cs/domain
/Users/alexandermostovenko/workspace/uaprom/node_modules/eslint-config-airbnb/rules/react.js:
	Configuration for rule "react/display-name" is invalid:
	Value "data["0"].ignoreTranspilerName" has additional properties.

Referenced from: airbnb
Referenced from: /Users/alexandermostovenko/workspace/uaprom/.eslintrc
Error: /Users/alexandermostovenko/workspace/uaprom/node_modules/eslint-config-airbnb/rules/react.js:
	Configuration for rule "react/display-name" is invalid:
	Value "data["0"].ignoreTranspilerName" has additional properties.

Referenced from: airbnb
Referenced from: /Users/alexandermostovenko/workspace/uaprom/.eslintrc
    at validateRuleOptions (/Users/alexandermostovenko/workspace/uaprom/node_modules/eslint/lib/config/config-validator.js:116:15)
    at /Users/alexandermostovenko/workspace/uaprom/node_modules/eslint/lib/config/config-validator.js:163:13
    at Array.forEach (native)
    at Object.validate (/Users/alexandermostovenko/workspace/uaprom/node_modules/eslint/lib/config/config-validator.js:162:35)
    at load (/Users/alexandermostovenko/workspace/uaprom/node_modules/eslint/lib/config/config-file.js:518:19)
    at /Users/alexandermostovenko/workspace/uaprom/node_modules/eslint/lib/config/config-file.js:386:36
    at Array.reduceRight (native)
    at applyExtends (/Users/alexandermostovemake: *** [lint] Error 1
```

here is my .eslintrc
```json
{
  "extends": "airbnb"
}
```

here are deps versions from package.json
```
    "eslint": "^2.10.2",
    "eslint-config-airbnb": "^9.0.1",
    "eslint-plugin-import": "^1.8.0",
    "eslint-plugin-jsx-a11y": "^1.2.2",
    "eslint-plugin-react": "^3.16.1",
```

**Comment by ljharb** [comment]
`eslint-plugin-react` is up to `v5.1.1`, and I'm quite sure that `npm ls` will report that you have an out of date version of `eslint-plugin-react`.

**Comment by AlexMost** [comment]
yep, missed that latest is 5.1.1. Thanks
