### ISSUE TITLE
Config invalid since 10.0.0

### ISSUE THREAD

**Issue by webdif** [airbnb/javascript#981]
I just update my project to grab all new versions:
```
...
    "eslint": "^3.2.2",
    "eslint-config-airbnb": "^10.0.0",
    "eslint-import-resolver-node": "^0.2.0",
    "eslint-plugin-import": "^1.12.0",
    "eslint-plugin-jsx-a11y": "^2.0.1",
    "eslint-plugin-react": "^6.0.0",
...
```

But I encounter this error:

```
Error: <project_path>/node_modules/eslint-config-airbnb/rules/react.js:
	Configuration for rule "react/jsx-sort-props" is invalid:
	Value "data["0"].shorthandLast" has additional properties.
Referenced from: airbnb
Referenced from: <project_path>/.eslintrc
    at validateRuleOptions (<project_path>/node_modules/eslint/lib/config/config-validator.js:116:15)
    at <project_path>/node_modules/eslint/lib/config/config-validator.js:163:13
    at Array.forEach (native)
    at Object.validate (<project_path>/node_modules/eslint/lib/config/config-validator.js:162:35)
    at load (<project_path>/node_modules/eslint/lib/config/config-file.js:523:19)
    at <project_path>/node_modules/eslint/lib/config/config-file.js:392:36
    at Array.reduceRight (native)
    at applyExtends (<project_path>/node_modules/eslint/lib/config/config-file.js:363:28)
    at load (<project_path>/node_modules/eslint/lib/config/config-file.js:530:22)
    at <project_path>/node_modules/eslint/lib/config/config-file.js:392:36
```

Any help?

**Comment by webdif** [comment]
A horrible `rm -rf node_modules && npm install` seems to fix this issue. Silly me!
